from .models import WordEntry, HashTable

hash_table = HashTable(1000)
hash_table.insert("Hello", WordEntry("xin chào", "https://media.makeameme.org/created/hello-sir-my-59f1d3.jpg", "https://dictionary.cambridge.org/vi/media/english/uk_pron/u/ukh/ukhef/ukheft_029.mp3"))
hash_table.insert("Football", WordEntry("Bóng đá", "https://images.indianexpress.com/2022/06/india-Football-pic-credit-aiff.jpg", "https://dictionary.cambridge.org/media/english/us_pron/f/foo/footb/football.mp3"))
hash_table.insert("Movie", WordEntry("Phim điện ảnh", "https://cdn.marvel.com/content/1x/antmanandthewaspquantumania_lob_crd_03.jpg", "https://dictionary.cambridge.org/media/english/uk_pron_ogg/u/ukm/ukmou/ukmourn022.ogg"))
hash_table.insert("Dog", WordEntry("Con chó", "https://dictionary.cambridge.org/images/thumb/dog_noun_001_04904.jpg", "https://dictionary.cambridge.org/media/english/us_pron_ogg/d/dog/dog__/dog.ogg"))
hash_table.insert("Run", WordEntry("Chạy đi", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Flickr_cc_runner_wisconsin_u.jpg/220px-Flickr_cc_runner_wisconsin_u.jpg", "https://dictionary.cambridge.org/vi/media/english/uk_pron/u/ukr/ukrum/ukrum__018.mp3"))
hash_table.insert("Cat", WordEntry("Con mèo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Computer", WordEntry("Máy tính", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Book", WordEntry("Sách", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Garden", WordEntry("Khu vườn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Tree", WordEntry("Cây", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sun", WordEntry("Mặt trời", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Moon", WordEntry("Mặt trăng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Star", WordEntry("Ngôi sao", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Ocean", WordEntry("Đại dương", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mountain", WordEntry("Núi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Chair", WordEntry("Ghế", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Table", WordEntry("Bàn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pen", WordEntry("Bút", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Paper", WordEntry("Giấy", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Rain", WordEntry("Mưa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sunset", WordEntry("Hoàng hôn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Fruit", WordEntry("Trái cây", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Vegetable", WordEntry("Rau cải", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Car", WordEntry("Xe hơi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bus", WordEntry("Xe buýt", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Train", WordEntry("Xe lửa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Airplane", WordEntry("Máy bay", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Boat", WordEntry("Thuyền", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Beach", WordEntry("Bãi biển", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mountain", WordEntry("Núi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Lake", WordEntry("Hồ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("River", WordEntry("Sông", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bridge", WordEntry("Cây cầu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Building", WordEntry("Toà nhà", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("City", WordEntry("Thành phố", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("School", WordEntry("Trường học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Teacher", WordEntry("Giáo viên", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Student", WordEntry("Học sinh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bookstore", WordEntry("Hiệu sách", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Library", WordEntry("Thư viện", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Computer", WordEntry("Máy tính", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Internet", WordEntry("Internet", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mobile", WordEntry("Điện thoại di động", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Friend", WordEntry("Bạn bè", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Family", WordEntry("Gia đình", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Love", WordEntry("Tình yêu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Happiness", WordEntry("Hạnh phúc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sadness", WordEntry("Buồn bã", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Anger", WordEntry("Tức giận", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Fear", WordEntry("Sợ hãi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Surprise", WordEntry("Ngạc nhiên", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Laugh", WordEntry("Cười", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cry", WordEntry("Khóc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sing", WordEntry("Hát", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Dance", WordEntry("Nhảy múa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Art", WordEntry("Nghệ thuật", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Science", WordEntry("Khoa học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("History", WordEntry("Lịch sử", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Geography", WordEntry("Địa lý", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Math", WordEntry("Toán học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Physics", WordEntry("Vật lý", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Chemistry", WordEntry("Hóa học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Biology", WordEntry("Sinh học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Economics", WordEntry("Kinh tế học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Environment", WordEntry("Môi trường", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pollution", WordEntry("Ô nhiễm", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Recycle", WordEntry("Tái chế", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Climate", WordEntry("Khí hậu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Global warming", WordEntry("Nóng lên toàn cầu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Renewable energy", WordEntry("Năng lượng tái tạo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Solar power", WordEntry("Năng lượng mặt trời", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Wind power", WordEntry("Năng lượng gió", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Electricity", WordEntry("Điện lực", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Water", WordEntry("Nước", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Air", WordEntry("Không khí", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Food", WordEntry("Thức ăn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Health", WordEntry("Sức khỏe", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Exercise", WordEntry("Tập thể dục", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Medicine", WordEntry("Thuốc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Doctor", WordEntry("Bác sĩ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Hospital", WordEntry("Bệnh viện", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sickness", WordEntry("Bệnh tật", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Vaccination", WordEntry("Tiêm chủng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pandemic", WordEntry("Dịch bệnh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Quarantine", WordEntry("Cách ly", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Social distancing", WordEntry("Giãn cách xã hội", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mask", WordEntry("Mặt nạ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Hygiene", WordEntry("Vệ sinh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Clean", WordEntry("Sạch sẽ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Dirty", WordEntry("Bẩn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Wash", WordEntry("Rửa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Soap", WordEntry("Xà phòng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Waterfall", WordEntry("Thác nước", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Volcano", WordEntry("Núi lửa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Desert", WordEntry("Sa mạc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Jungle", WordEntry("Rừng nhiệt đới", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mountain range", WordEntry("Dãy núi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Island", WordEntry("Đảo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Beach", WordEntry("Bãi biển", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cave", WordEntry("Hang động", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Rainforest", WordEntry("Rừng mưa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Meadow", WordEntry("Đồng cỏ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Savanna", WordEntry("Savana", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Tundra", WordEntry("Đất đáng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Arctic", WordEntry("Vùng Bắc Cực", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Ant", WordEntry("Kiến", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bee", WordEntry("Ong", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Butterfly", WordEntry("Bướm", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Spider", WordEntry("Nhện", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Snail", WordEntry("Ốc sên", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Fish", WordEntry("Cá", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Dolphin", WordEntry("Cá heo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Shark", WordEntry("Cá mập", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Whale", WordEntry("Cá voi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Octopus", WordEntry("Bạch tuộc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Penguin", WordEntry("Chim cánh cụt", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Elephant", WordEntry("Voi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Lion", WordEntry("Sư tử", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Tiger", WordEntry("Hổ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Giraffe", WordEntry("Hươu cao cổ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Kangaroo", WordEntry("Kangaroo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Zebra", WordEntry("Ngựa vằn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Monkey", WordEntry("Khỉ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Gorilla", WordEntry("Gorilla", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Panda", WordEntry("Gấu trúc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Koala", WordEntry("Koala", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Horse", WordEntry("Ngựa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cow", WordEntry("Bò", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sheep", WordEntry("Cừu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Goat", WordEntry("Dê", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pig", WordEntry("Heo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Chicken", WordEntry("Gà", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Duck", WordEntry("Vịt", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Owl", WordEntry("Cú mèo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Eagle", WordEntry("Đại bàng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Parrot", WordEntry("Vẹt", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Squirrel", WordEntry("Sóc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Rabbit", WordEntry("Thỏ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Fox", WordEntry("Cáo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bear", WordEntry("Gấu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Deer", WordEntry("Hươu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Hedgehog", WordEntry("Nhím", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Seagull", WordEntry("Mòng biển", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Dinosaur", WordEntry("Khủng long", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Dragonfly", WordEntry("Châu chấu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Ladybug", WordEntry("Bọ rùa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Caterpillar", WordEntry("Sâu bướm", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mosquito", WordEntry("Muỗi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Centipede", WordEntry("Rết", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Beehive", WordEntry("Tổ ong", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Spiderweb", WordEntry("Mạng nhện", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Rose", WordEntry("Hoa hồng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Lily", WordEntry("Hoa Lily", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Tulip", WordEntry("Hoa tulip", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sunflower", WordEntry("Hoa hướng dương", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Daisy", WordEntry("Hoa cúc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Orchid", WordEntry("Hoa lan", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Daffodil", WordEntry("Hoa thủy tiên", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cherry blossom", WordEntry("Hoa anh đào", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Maple tree", WordEntry("Cây phong", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pine tree", WordEntry("Cây thông", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Oak tree", WordEntry("Cây sồi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bamboo", WordEntry("Trúc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Rainbow", WordEntry("Cầu vồng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cloud", WordEntry("Đám mây", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Moonlight", WordEntry("Ánh trăng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Starlight", WordEntry("Ánh sao", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Galaxy", WordEntry("Ngân hà", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Universe", WordEntry("Vũ trụ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Astronomy", WordEntry("Thiên văn học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Telescope", WordEntry("Kính thiên văn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Meteor", WordEntry("Sao băng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Comet", WordEntry("Sao chổi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Satellite", WordEntry("Vệ tinh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Rocket", WordEntry("Tên lửa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Space station", WordEntry("Trạm không gian", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Alien", WordEntry("Người ngoài hành tinh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Spacecraft", WordEntry("Tàu vũ trụ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Black hole", WordEntry("Lỗ đen", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Big Bang", WordEntry("Sự nổ lớn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Gravity", WordEntry("Trọng lực", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Light", WordEntry("Ánh sáng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sound", WordEntry("Âm thanh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Time", WordEntry("Thời gian", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Space", WordEntry("Không gian", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Earth", WordEntry("Trái đất", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mars", WordEntry("Hỏa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Jupiter", WordEntry("Mộc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Saturn", WordEntry("Thổ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Uranus", WordEntry("Hải vương", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Neptune", WordEntry("Hải trung", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bacteria", WordEntry("Vi khuẩn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Virus", WordEntry("Vi-rút", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Fungus", WordEntry("Nấm", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Protozoa", WordEntry("Nguyên đơn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Algae", WordEntry("Tảo biển", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mold", WordEntry("Nấm mốc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Yeast", WordEntry("Men bia", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Amoeba", WordEntry("Sinh vật tiểu trùng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Parasite", WordEntry("Ký sinh trùng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Microorganism", WordEntry("Vi sinh vật", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pathogen", WordEntry("Chất gây bệnh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Antibiotic", WordEntry("Thuốc kháng sinh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Immunity", WordEntry("Sức đề kháng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Vaccine", WordEntry("Vắc xin", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Microscope", WordEntry("Kính hiển vi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cell", WordEntry("Tế bào", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("DNA", WordEntry("ADN", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("RNA", WordEntry("ARN", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mutation", WordEntry("Đột biến gen", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Genome", WordEntry("Genôm", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Evolution", WordEntry("Tiến hóa", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Adaptation", WordEntry("Adaptation", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Biology", WordEntry("Sinh học học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Ecology", WordEntry("Sinh thái học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Ecosystem", WordEntry("Hệ sinh thái", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Natural selection", WordEntry("Tự nhiên chọn lọc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Extinction", WordEntry("Sự tuyệt chủng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Habitat", WordEntry("Môi trường sống", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Biodiversity", WordEntry("Đa dạng sinh học", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Conservation", WordEntry("Bảo tồn", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Climate change", WordEntry("Biến đổi khí hậu", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Deforestation", WordEntry("Phá rừng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pollination", WordEntry("Best thụ tinh", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Insect", WordEntry("Sâu bọ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mammal", WordEntry("Thú có vú", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Reptile", WordEntry("Bò sát", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Amphibian", WordEntry("Lưỡng cư", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bird", WordEntry("Chim", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Plant", WordEntry("Thực vật", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Photosynthesis", WordEntry("Quang hợp", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Respiration", WordEntry("Hô hấp", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Fermentation", WordEntry("Lên men", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Enzyme", WordEntry("Enzyme", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Mitosis", WordEntry("Giảm phân", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Meiosis", WordEntry("Trung phân", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Chlorophyll", WordEntry("Lôi sáng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cell membrane", WordEntry("Màng tế bào", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Nucleus", WordEntry("Nhân tế bào", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cytoplasm", WordEntry("Tế bào chất", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Organelle", WordEntry("Bào quan", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Bioluminescence", WordEntry("Tự sáng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Plankton", WordEntry("Phytoplankton", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Zooplankton", WordEntry("Zooplankton", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Coral", WordEntry("San hô", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Seaweed", WordEntry("Tảo biển", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Ammonia", WordEntry("Ammoniac", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Agaricus bisporus", WordEntry("Nấm mỡ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Amanita muscaria", WordEntry("Nấm độc độc", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Boletus edulis", WordEntry("Nấm linh chi", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cordyceps militaris", WordEntry("Nấm rồng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Truffle", WordEntry("Nấm truffle", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Morel", WordEntry("Nấm Morel", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Chanterelle", WordEntry("Nấm chanterelle", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Shiitake", WordEntry("Nấm shiitake", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Maitake", WordEntry("Nấm maitake", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Enoki", WordEntry("Nấm enoki", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Oyster mushroom", WordEntry("Nấm mọc trên cây dương", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Reishi", WordEntry("Nấm linh chi đỏ", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Lion's mane", WordEntry("Nấm bồ ngô", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Porcini", WordEntry("Nấm porcini", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pholiota nameko", WordEntry("Nấm nameko", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Crimini", WordEntry("Nấm crimini", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Shimeji", WordEntry("Nấm shimeji", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Lentinula edodes", WordEntry("Nấm mèo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Agaricus blazei", WordEntry("Nấm himematsutake", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Agaricus subrufescens", WordEntry("Nấm almondy", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Pleurotus ostreatus", WordEntry("Nấm bào ngư", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Flammulina velutipes", WordEntry("Nấm kim châm", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Auricularia auricula-judae", WordEntry("Nấm mèo tai heo", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Tremella fuciformis", WordEntry("Nấm mèo tai gà", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Morchella", WordEntry("Nấm morel đen", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Tuber magnatum", WordEntry("Nấm truffle trắng", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Clavariaceae", WordEntry("Nấm club", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Ramaria", WordEntry("Nấm coral", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Sparassis", WordEntry("Nấm cauliflower", "link_hình_ảnh", "link_nghe_âm_thanh"))
hash_table.insert("Cordyceps sinensis", WordEntry("Nấm đông trùng hạ thảo", "link_hình_ảnh", "link_nghe_âm_thanh"))