# Generated by Django 4.2.4 on 2023-09-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=100)),
                ('vietnam', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=200)),
                ('pronounce', models.CharField(max_length=50)),
            ],
        ),
    ]
