# Generated by Django 4.2.4 on 2023-09-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='pronounce',
            field=models.CharField(max_length=200),
        ),
    ]
