# Generated by Django 4.2.4 on 2023-09-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'verbose_name_plural': 'Dictionary Entries'},
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='english',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
